[package]
name = "native"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
solana-program = "1.8.2"
solana-sdk = "1.8.2"
solana-client = "1.8.2"
borsh = "0.9.1"
borsh-derive = "0.9.1"
owo-colors = "3.1.0"
